### PR TITLE
Create `MLJEnsembles` module

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by giordano** [comment]
This is truly bizarre: tests fail on Julia v1.1 because the resolver can't find an optimal solution including `MLJModels` when `MLJModels` is listed as test dependency, however it'd find the solution if the package was listed as a main dependency, which ideally would be the same situation.

**Comment by ablaom** [comment]
I don't see bumping to Julia 1.2 as a major issue. However, it might anyway make sense to dump MLJModels as a dependency. It is not a dependency of MLJBase which instead imports its own local [model interfaces](https://github.com/alan-turing-institute/MLJBase.jl/tree/dev/test/_models) for testing. We have done the same thing in MLJTuning. Indeed, I have thought that for better maintenance, we should probably have a single "test repo" for this purpose (the MLJBase version has already diverged a bit from the MLJTuning one). So, if you are up for that....  One would want to check that the test models you need are already in the MLJBase suite.

**Comment by ablaom** [comment]
Also, could we have a separate ci_nighlty.yml, as in MLJFlux.jl, to avoid failing badges. Be sure to [update action name](https://github.com/FluxML/MLJFlux.jl/pull/150/commits/8f679e6862aee8bc7f0807d4aa3ce411d8d13924).

**Review by ablaom — APPROVED** [review]
@giordano This looks good to me. Many thanks.

**Pull request merged**
